#!/usr/bin/env python3
"""Regenerates hooks/sprites.ts from assets/isaac/*.png.

The desktop strips embedded images from a plugin's SVG, so each sprite is
turned into vector paths: one path per colour, one rectangle per horizontal
run of same-coloured pixels. Run this after changing any PNG (needs Pillow):

    python3 scripts/build-sprites.py
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
STATES = ["green", "yellow", "red", "limit"]


def sprite_paths(path: Path) -> tuple[int, int, list[tuple[str, str]]]:
    image = Image.open(path).convert("RGBA")
    width, height = image.size
    pixels = image.load()
    runs: dict[str, list[str]] = {}
    for y in range(height):
        x = 0
        while x < width:
            r, g, b, a = pixels[x, y]
            if a == 0:
                x += 1
                continue
            start = x
            while x < width and pixels[x, y] == (r, g, b, a):
                x += 1
            fill = f"#{r:02x}{g:02x}{b:02x}" + (f"{a:02x}" if a < 255 else "")
            runs.setdefault(fill, []).append(f"M{start} {y}h{x - start}v1h-{x - start}z")
    return width, height, [(fill, "".join(parts)) for fill, parts in runs.items()]


lines = [
    "// Generated by scripts/build-sprites.py from assets/isaac/*.png. Do not edit.",
    "",
    "export type Sprite = { width: number; height: number; paths: readonly (readonly [fill: string, d: string])[] }",
    "",
    "export const SPRITES = {",
]
for state in STATES:
    width, height, paths = sprite_paths(ROOT / "assets" / "isaac" / f"{state}.png")
    body = ", ".join(f"['{fill}', '{d}']" for fill, d in paths)
    lines.append(f"  {state}: {{ width: {width}, height: {height}, paths: [{body}] }},")
lines += ["} satisfies Record<string, Sprite>", ""]

(ROOT / "hooks" / "sprites.ts").write_text("\n".join(lines))
print("wrote hooks/sprites.ts")
